default: &default
  adapter: postgresql
  encoding: unicode
  username:
  password:
  pool: 5
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] %>
  
development:
  <<: *default
  database: riagoncalves_dev

test:
  <<: *default
  database: riagoncalves_test

production:
  <<: *default
  database: riagoncalves_produc